name: Build and deploy workfLow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t where456/skypro_homework:$GITHUB_REF_NAME-$GITHUB_RUN_ID .